<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250923213709 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE group_player DROP CONSTRAINT fk_4b9fa2b5fe54d947');
        $this->addSql('ALTER TABLE group_player DROP CONSTRAINT fk_4b9fa2b599e6f5df');
        $this->addSql('ALTER TABLE interfac_match DROP CONSTRAINT fk_3b918c5df88398a7');
        $this->addSql('ALTER TABLE interfac_match DROP CONSTRAINT fk_3b918c5df920b9e9');
        $this->addSql('ALTER TABLE interfac_match_player DROP CONSTRAINT fk_8116b032121b0c7d');
        $this->addSql('ALTER TABLE interfac_match_player DROP CONSTRAINT fk_8116b03299e6f5df');
        $this->addSql('ALTER TABLE time_slot DROP CONSTRAINT fk_1b3294ab897366b');
        $this->addSql('ALTER TABLE time_slot DROP CONSTRAINT fk_1b3294a5eeadd3b');
        $this->addSql('ALTER TABLE time_slot DROP CONSTRAINT fk_1b3294acb258cd2');
        $this->addSql('DROP TABLE date');
        $this->addSql('DROP TABLE "group"');
        $this->addSql('DROP TABLE group_player');
        $this->addSql('DROP TABLE interfac_match');
        $this->addSql('DROP TABLE interfac_match_player');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE "time"');
        $this->addSql('DROP TABLE time_slot');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE date (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "group" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE group_player (group_id INT NOT NULL, player_id INT NOT NULL, PRIMARY KEY (group_id, player_id))');
        $this->addSql('CREATE INDEX idx_4b9fa2b5fe54d947 ON group_player (group_id)');
        $this->addSql('CREATE INDEX idx_4b9fa2b599e6f5df ON group_player (player_id)');
        $this->addSql('CREATE TABLE interfac_match (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, player_group_id INT NOT NULL, timeslot_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_3b918c5df88398a7 ON interfac_match (player_group_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_3b918c5df920b9e9 ON interfac_match (timeslot_id)');
        $this->addSql('CREATE TABLE interfac_match_player (interfac_match_id INT NOT NULL, player_id INT NOT NULL, PRIMARY KEY (interfac_match_id, player_id))');
        $this->addSql('CREATE INDEX idx_8116b032121b0c7d ON interfac_match_player (interfac_match_id)');
        $this->addSql('CREATE INDEX idx_8116b03299e6f5df ON interfac_match_player (player_id)');
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) DEFAULT NULL, ranking VARCHAR(255) DEFAULT NULL, gender VARCHAR(255) NOT NULL, birthyear VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "time" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "time" TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE time_slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_id INT NOT NULL, time_id INT NOT NULL, end_time_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_1b3294ab897366b ON time_slot (date_id)');
        $this->addSql('CREATE INDEX idx_1b3294a5eeadd3b ON time_slot (time_id)');
        $this->addSql('CREATE INDEX idx_1b3294acb258cd2 ON time_slot (end_time_id)');
        $this->addSql('ALTER TABLE group_player ADD CONSTRAINT fk_4b9fa2b5fe54d947 FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_player ADD CONSTRAINT fk_4b9fa2b599e6f5df FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE interfac_match ADD CONSTRAINT fk_3b918c5df88398a7 FOREIGN KEY (player_group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE interfac_match ADD CONSTRAINT fk_3b918c5df920b9e9 FOREIGN KEY (timeslot_id) REFERENCES time_slot (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE interfac_match_player ADD CONSTRAINT fk_8116b032121b0c7d FOREIGN KEY (interfac_match_id) REFERENCES interfac_match (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE interfac_match_player ADD CONSTRAINT fk_8116b03299e6f5df FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE time_slot ADD CONSTRAINT fk_1b3294ab897366b FOREIGN KEY (date_id) REFERENCES date (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE time_slot ADD CONSTRAINT fk_1b3294a5eeadd3b FOREIGN KEY (time_id) REFERENCES "time" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE time_slot ADD CONSTRAINT fk_1b3294acb258cd2 FOREIGN KEY (end_time_id) REFERENCES "time" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
